# -- Site Configuration --

theme: blowfish
baseURL: https://csanford.cloud/
defaultContentLanguage: en

pluralizeListTitles: true

enableRobotsTXT: true
summaryLength: 50

buildDrafts: false
buildFuture: false

enableEmoji: true

# googleAnalytics: "G-XXXXXXXXX"

pagination:
  pagerSize: 100

imaging:
  anchor: Center

taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series

sitemap:
  changefreq: "daily"
  filename: "sitemap.xml"
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON
  # page:
  #   - HTML
  # section:
  #   - HTML
  #   - RSS
  #   - RSS
  # term:
  #   - HTML
  #   - RSS

related:
  threshold: 0
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 100
    - name: series
      weight: 50
    - name: date
      weight: 10
    - name: fragmentrefs
      type: fragments
      weight: 10
      applyFilter: false
