# -- Markup --
# These settings are required for the theme to function.

goldmark:
  renderer:
    unsafe: true

highlight:
  noClasses: false
  # style: dracula
  # guessSyntax: true
  # lineNumbersInTable: true

tableOfContents:
  startLevel: 2
  endLevel: 4
  # ordered: false